# permissions for end users to view firewalls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: firewall-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: osdks
    app.kubernetes.io/part-of: osdks
    app.kubernetes.io/managed-by: kustomize
  name: firewall-viewer-role
rules:
- apiGroups:
  - cloud.bizflycloud.vn
  resources:
  - firewalls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.bizflycloud.vn
  resources:
  - firewalls/status
  verbs:
  - get
