# permissions for end users to edit firewalls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: firewall-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: osdks
    app.kubernetes.io/part-of: osdks
    app.kubernetes.io/managed-by: kustomize
  name: firewall-editor-role
rules:
- apiGroups:
  - cloud.bizflycloud.vn
  resources:
  - firewalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.bizflycloud.vn
  resources:
  - firewalls/status
  verbs:
  - get
